import neuroscience_decision_making_neuroscience_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace neuroscience_decision_making_neuroscience_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end neuroscience_decision_making_neuroscience_theorem_canonical_lane_mathlib
end HautevilleHouse
